INSERT INTO USER_DETAILS (ID, USER_EMAIL, PASSWORD) VALUES('1','abc','123') ;
INSERT INTO USER_DETAILS (ID, USER_EMAIL, PASSWORD) VALUES('2','amalav','123456') ;

--INSERT INTO Expressions (USER_EMAIL, ADD_COUNT, SUBTRACT_COUNT, MULTIPLY_COUNT, DIVIDE_COUNT) VALUES('amalav','0', '0','0','0') ;
--INSERT INTO Expressions (USER_EMAIL, ADD_COUNT, SUBTRACT_COUNT, MULTIPLY_COUNT, DIVIDE_COUNT) VALUES('2','Goa', '1') ;
--INSERT INTO Expressions (USER_EMAIL, ADD_COUNT, SUBTRACT_COUNT, MULTIPLY_COUNT, DIVIDE_COUNT) VALUES('3','Kota', '1') ;
--INSERT INTO Expressions (USER_EMAIL, ADD_COUNT, SUBTRACT_COUNT, MULTIPLY_COUNT, DIVIDE_COUNT) VALUES('4','Banglore', '1') ;
